name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag caddy-super:latest
    - name: Push the Docker image
      run: docker login -u jaziel826 -p ${{ secrets.DOCKER_TOKEN }} && docker push jaziel826/caddy-super:latest
